### ISSUE TITLE
How long would it take to fine-tune a model using a consumer GPU, the 4070 Ti Super with 16GB of VRAM?

### ISSUE THREAD

**Issue by neozhu** [Atharva-Weginwar/FineTuning_Google_Gemma#1]
Have you ever tried testing on a consumer graphics card?

**Comment by Atharva-Weginwar** [comment]
Yes i have used google colab T4 GPU to fine tune this.

**Comment by Atharva-Weginwar** [comment]
Yes i have used google colab T4 GPU to fine tune this.
